name: petbook_admin
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'


dependencies:
  cloud_firestore: ^4.3.1
  location: ^4.4.0
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  firebase_storage: ^11.0.10
  flutter:
    sdk: flutter
  google_fonts: 2.2.0
  google_maps_flutter: ^2.2.3
  google_maps_webservice: ^0.0.19
  flutter_staggered_grid_view: ^0.4.0
  http: ^0.13.5
  image_picker: ^0.8.6
  intl: ^0.18.0
  provider: ^6.0.5
  uuid: ^3.0.7
  flutter_svg: ^1.1.6
  shared_preferences: ^2.0.20
  rating_dialog: ^2.0.4
  geolocator: ^9.0.2


  cupertino_icons: ^1.0.2
  firebase_messaging: ^14.6.0
  flutter_local_notifications: ^14.0.0+2
  get: ^4.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.2

flutter:

  uses-material-design: true
  assets:
    - assets/
